"""update access_code length to 7

Revision ID: 05e9978a4a36
Revises: 476a51095132
Create Date: 2026-06-10 11:18:33.265579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05e9978a4a36'
down_revision: Union[str, Sequence[str], None] = '476a51095132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_codes', 'code',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=7),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_codes', 'code',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###
