"""create coaches and students tables

Revision ID: 2b00bc1404da
Revises: 2d696f003acc
Create Date: 2026-04-27 23:07:39.790713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b00bc1404da'
down_revision: Union[str, Sequence[str], None] = '2d696f003acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('genero', sa.Enum('masculino', 'feminino', 'outro', name='studentgenero'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('coach_id', sa.String(), nullable=False),
    sa.Column('payment_plan_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['payment_plan_id'], ['planos_pagamento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
