"""create coaches table

Revision ID: 2d696f003acc
Revises: 505d7b9b02f3
Create Date: 2026-04-27 13:20:12.709300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d696f003acc'
down_revision: Union[str, Sequence[str], None] = '505d7b9b02f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('especialidade', sa.Enum('musculacao', 'crossfit', 'yoga', 'pilates', 'natacao', 'funcional', name='coachespecialidade'), nullable=False),
    sa.Column('genero', sa.Enum('masculino', 'feminino', 'outro', name='coachgenero'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coaches')
    # ### end Alembic commands ###
