"""create attendances table

Revision ID: 476a51095132
Revises: 99a9313696cd
Create Date: 2026-06-03 11:28:29.959493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '476a51095132'
down_revision: Union[str, Sequence[str], None] = '99a9313696cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attendances_token_key'), 'attendances', type_='unique')
    op.drop_column('attendances', 'token_expira_em')
    op.drop_column('attendances', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('token', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('attendances', sa.Column('token_expira_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('attendances_token_key'), 'attendances', ['token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
