"""create payments table

Revision ID: 4f8e960b1926
Revises: 7b3db3404c5a
Create Date: 2026-04-28 12:57:12.514345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f8e960b1926'
down_revision: Union[str, Sequence[str], None] = '7b3db3404c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('payment_plan_id', sa.String(length=36), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pago', 'pendente', 'atrasado', name='paymentstatus'), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['payment_plan_id'], ['planos_pagamento.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###
