"""add data_inicio and data_fim to students

Revision ID: 660ee1745c35
Revises: 93a60ce842a9
Create Date: 2026-05-19 11:26:56.792886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '660ee1745c35'
down_revision: Union[str, Sequence[str], None] = '93a60ce842a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('data_inicio', sa.DateTime(), nullable=False))
    op.add_column('students', sa.Column('data_fim', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'data_fim')
    op.drop_column('students', 'data_inicio')
    # ### end Alembic commands ###
