"""add access_codes table remove activation_token

Revision ID: 93a60ce842a9
Revises: d538be6447f2
Create Date: 2026-05-14 20:40:56.666080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93a60ce842a9'
down_revision: Union[str, Sequence[str], None] = 'd538be6447f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.drop_constraint(op.f('students_activation_token_key'), 'students', type_='unique')
    op.drop_column('students', 'activation_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('activation_token', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('students_activation_token_key'), 'students', ['activation_token'], postgresql_nulls_not_distinct=False)
    op.drop_table('access_codes')
    # ### end Alembic commands ###
