"""create payments table

Revision ID: 99a9313696cd
Revises: 7ae6cdaff313
Create Date: 2026-05-24 23:05:33.935837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99a9313696cd'
down_revision: Union[str, Sequence[str], None] = '7ae6cdaff313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'data_inicio',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('students', 'data_fim',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'data_fim',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('students', 'data_inicio',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
