"""create coach_experiencias table

Revision ID: c5fa90132914
Revises: 7db785189ea5
Create Date: 2026-06-15 10:37:14.177701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5fa90132914'
down_revision: Union[str, Sequence[str], None] = '7db785189ea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_experiencias',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('coach_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.Enum('musculacao', 'crossfit', 'yoga', 'pilates', 'natacao', 'funcional', 'boxe', 'artes_marciais', 'spinning', 'zumba', 'calistenia', 'alongamento', 'atletismo', 'nutricao_esportiva', name='experiencianome'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coach_experiencias')
    # ### end Alembic commands ###
