"""add activation_token to students

Revision ID: d538be6447f2
Revises: ef1cac266d38
Create Date: 2026-05-05 19:25:04.610577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd538be6447f2'
down_revision: Union[str, Sequence[str], None] = 'ef1cac266d38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('activation_token', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'students', ['activation_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'activation_token')
    # ### end Alembic commands ###
