"""create attendances table

Revision ID: ef1cac266d38
Revises: 4f8e960b1926
Create Date: 2026-04-28 14:06:30.396830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1cac266d38'
down_revision: Union[str, Sequence[str], None] = '4f8e960b1926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('token_expira_em', sa.DateTime(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora_entrada', sa.Time(), nullable=True),
    sa.Column('hora_saida', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('pendente_entrada', 'presente', 'pendente_saida', 'saiu', name='attendancestatus'), nullable=False),
    sa.Column('confirmado_entrada_em', sa.DateTime(), nullable=True),
    sa.Column('confirmado_saida_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendances')
    # ### end Alembic commands ###
